name: Build Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      - name: Configure & Build
        uses: threeal/cmake-action@v2.1.0
        with:
          build-dir: build